#!/bin/bash
(CUDA_VISIBLE_DEVICES=0 python -m lsh.train_hashcode dataset.name="msweb294" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.05  hashcode_training.QA_MARGIN=1.0) & 
(CUDA_VISIBLE_DEVICES=0 python -m lsh.train_hashcode dataset.name="msweb294" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.1  hashcode_training.QA_MARGIN=1.0) & 
(CUDA_VISIBLE_DEVICES=0 python -m lsh.train_hashcode dataset.name="msweb294" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.15  hashcode_training.QA_MARGIN=1.0) & 
(CUDA_VISIBLE_DEVICES=0 python -m lsh.train_hashcode dataset.name="msweb294" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.2  hashcode_training.QA_MARGIN=1.0) & 
(CUDA_VISIBLE_DEVICES=0 python -m lsh.train_hashcode dataset.name="msweb294" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.25  hashcode_training.QA_MARGIN=1.0) & 
(CUDA_VISIBLE_DEVICES=0 python -m lsh.train_hashcode dataset.name="msweb294" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.3  hashcode_training.QA_MARGIN=1.0) & 
(CUDA_VISIBLE_DEVICES=0 python -m lsh.train_hashcode dataset.name="msweb294" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.35  hashcode_training.QA_MARGIN=1.0) & 
(CUDA_VISIBLE_DEVICES=0 python -m lsh.train_hashcode dataset.name="msweb294" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.4  hashcode_training.QA_MARGIN=1.0) & 
(CUDA_VISIBLE_DEVICES=0 python -m lsh.train_hashcode dataset.name="msweb294" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.45  hashcode_training.QA_MARGIN=1.0) & 
(CUDA_VISIBLE_DEVICES=0 python -m lsh.train_hashcode dataset.name="msweb294" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.5  hashcode_training.QA_MARGIN=1.0) & 
(CUDA_VISIBLE_DEVICES=0 python -m lsh.train_hashcode dataset.name="msweb294" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.55  hashcode_training.QA_MARGIN=1.0) & 
(CUDA_VISIBLE_DEVICES=0 python -m lsh.train_hashcode dataset.name="msweb294" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.6  hashcode_training.QA_MARGIN=1.0) & 
(CUDA_VISIBLE_DEVICES=0 python -m lsh.train_hashcode dataset.name="msweb294" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.65  hashcode_training.QA_MARGIN=1.0) & 
(CUDA_VISIBLE_DEVICES=0 python -m lsh.train_hashcode dataset.name="msweb294" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.7  hashcode_training.QA_MARGIN=1.0) & 
(CUDA_VISIBLE_DEVICES=0 python -m lsh.train_hashcode dataset.name="msweb294" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.75  hashcode_training.QA_MARGIN=1.0) & 
(CUDA_VISIBLE_DEVICES=0 python -m lsh.train_hashcode dataset.name="msweb294" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.8  hashcode_training.QA_MARGIN=1.0) & 
(CUDA_VISIBLE_DEVICES=0 python -m lsh.train_hashcode dataset.name="msweb294" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.85  hashcode_training.QA_MARGIN=1.0) & 

(CUDA_VISIBLE_DEVICES=0 python -m lsh.train_hashcode dataset.name="msweb294_1" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.05  hashcode_training.QA_MARGIN=1.0) & 
(CUDA_VISIBLE_DEVICES=0 python -m lsh.train_hashcode dataset.name="msweb294_1" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.1  hashcode_training.QA_MARGIN=1.0) & 
(CUDA_VISIBLE_DEVICES=0 python -m lsh.train_hashcode dataset.name="msweb294_1" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.15  hashcode_training.QA_MARGIN=1.0) & 
(CUDA_VISIBLE_DEVICES=0 python -m lsh.train_hashcode dataset.name="msweb294_1" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.2  hashcode_training.QA_MARGIN=1.0) & 
(CUDA_VISIBLE_DEVICES=0 python -m lsh.train_hashcode dataset.name="msweb294_1" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.25  hashcode_training.QA_MARGIN=1.0) & 
(CUDA_VISIBLE_DEVICES=0 python -m lsh.train_hashcode dataset.name="msweb294_1" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.3  hashcode_training.QA_MARGIN=1.0) & 
(CUDA_VISIBLE_DEVICES=0 python -m lsh.train_hashcode dataset.name="msweb294_1" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.35  hashcode_training.QA_MARGIN=1.0) & 
(CUDA_VISIBLE_DEVICES=0 python -m lsh.train_hashcode dataset.name="msweb294_1" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.4  hashcode_training.QA_MARGIN=1.0) & 
(CUDA_VISIBLE_DEVICES=0 python -m lsh.train_hashcode dataset.name="msweb294_1" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.45  hashcode_training.QA_MARGIN=1.0) & 
(CUDA_VISIBLE_DEVICES=0 python -m lsh.train_hashcode dataset.name="msweb294_1" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.5  hashcode_training.QA_MARGIN=1.0) & 
(CUDA_VISIBLE_DEVICES=0 python -m lsh.train_hashcode dataset.name="msweb294_1" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.55  hashcode_training.QA_MARGIN=1.0) & 
(CUDA_VISIBLE_DEVICES=0 python -m lsh.train_hashcode dataset.name="msweb294_1" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.6  hashcode_training.QA_MARGIN=1.0) & 
(CUDA_VISIBLE_DEVICES=0 python -m lsh.train_hashcode dataset.name="msweb294_1" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.65  hashcode_training.QA_MARGIN=1.0) & 
(CUDA_VISIBLE_DEVICES=0 python -m lsh.train_hashcode dataset.name="msweb294_1" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.7  hashcode_training.QA_MARGIN=1.0) & 
(CUDA_VISIBLE_DEVICES=0 python -m lsh.train_hashcode dataset.name="msweb294_1" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.75  hashcode_training.QA_MARGIN=1.0) & 
(CUDA_VISIBLE_DEVICES=0 python -m lsh.train_hashcode dataset.name="msweb294_1" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.8  hashcode_training.QA_MARGIN=1.0) & 
(CUDA_VISIBLE_DEVICES=0 python -m lsh.train_hashcode dataset.name="msweb294_1" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.85  hashcode_training.QA_MARGIN=1.0) & 


# (CUDA_VISIBLE_DEVICES=2 python -m lsh.train_hashcode dataset.name="msnbc294_3" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.05  hashcode_training.QA_MARGIN=1.0) & 
# (CUDA_VISIBLE_DEVICES=2 python -m lsh.train_hashcode dataset.name="msnbc294_3" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.1  hashcode_training.QA_MARGIN=1.0) & 
# (CUDA_VISIBLE_DEVICES=2 python -m lsh.train_hashcode dataset.name="msnbc294_3" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.15  hashcode_training.QA_MARGIN=1.0) & 
# (CUDA_VISIBLE_DEVICES=2 python -m lsh.train_hashcode dataset.name="msnbc294_3" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.2  hashcode_training.QA_MARGIN=1.0) & 
# (CUDA_VISIBLE_DEVICES=2 python -m lsh.train_hashcode dataset.name="msnbc294_3" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.25  hashcode_training.QA_MARGIN=1.0) & 
# (CUDA_VISIBLE_DEVICES=2 python -m lsh.train_hashcode dataset.name="msnbc294_3" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.3  hashcode_training.QA_MARGIN=1.0) & 
# (CUDA_VISIBLE_DEVICES=2 python -m lsh.train_hashcode dataset.name="msnbc294_3" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.35  hashcode_training.QA_MARGIN=1.0) & 
# (CUDA_VISIBLE_DEVICES=2 python -m lsh.train_hashcode dataset.name="msnbc294_3" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.4  hashcode_training.QA_MARGIN=1.0) & 
# (CUDA_VISIBLE_DEVICES=2 python -m lsh.train_hashcode dataset.name="msnbc294_3" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.45  hashcode_training.QA_MARGIN=1.0) & 
# (CUDA_VISIBLE_DEVICES=2 python -m lsh.train_hashcode dataset.name="msnbc294_3" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.5  hashcode_training.QA_MARGIN=1.0) & 
# (CUDA_VISIBLE_DEVICES=2 python -m lsh.train_hashcode dataset.name="msnbc294_3" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.55  hashcode_training.QA_MARGIN=1.0) & 
# (CUDA_VISIBLE_DEVICES=2 python -m lsh.train_hashcode dataset.name="msnbc294_3" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.6  hashcode_training.QA_MARGIN=1.0) & 
# (CUDA_VISIBLE_DEVICES=2 python -m lsh.train_hashcode dataset.name="msnbc294_3" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.65  hashcode_training.QA_MARGIN=1.0) & 
# (CUDA_VISIBLE_DEVICES=2 python -m lsh.train_hashcode dataset.name="msnbc294_3" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.7  hashcode_training.QA_MARGIN=1.0) & 
# (CUDA_VISIBLE_DEVICES=2 python -m lsh.train_hashcode dataset.name="msnbc294_3" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.75  hashcode_training.QA_MARGIN=1.0) & 
# (CUDA_VISIBLE_DEVICES=2 python -m lsh.train_hashcode dataset.name="msnbc294_3" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.8  hashcode_training.QA_MARGIN=1.0) & 
# (CUDA_VISIBLE_DEVICES=2 python -m lsh.train_hashcode dataset.name="msnbc294_3" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.85  hashcode_training.QA_MARGIN=1.0) & 


# (CUDA_VISIBLE_DEVICES=1 python -m lsh.train_hashcode dataset.name="msnbc294_4" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.05  hashcode_training.QA_MARGIN=1.0) & 
# (CUDA_VISIBLE_DEVICES=1 python -m lsh.train_hashcode dataset.name="msnbc294_4" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.1  hashcode_training.QA_MARGIN=1.0) & 
# (CUDA_VISIBLE_DEVICES=1 python -m lsh.train_hashcode dataset.name="msnbc294_4" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.15  hashcode_training.QA_MARGIN=1.0) & 
# (CUDA_VISIBLE_DEVICES=1 python -m lsh.train_hashcode dataset.name="msnbc294_4" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.2  hashcode_training.QA_MARGIN=1.0) & 
# (CUDA_VISIBLE_DEVICES=1 python -m lsh.train_hashcode dataset.name="msnbc294_4" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.25  hashcode_training.QA_MARGIN=1.0) & 
# (CUDA_VISIBLE_DEVICES=1 python -m lsh.train_hashcode dataset.name="msnbc294_4" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.3  hashcode_training.QA_MARGIN=1.0) & 
# (CUDA_VISIBLE_DEVICES=1 python -m lsh.train_hashcode dataset.name="msnbc294_4" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.35  hashcode_training.QA_MARGIN=1.0) & 
# (CUDA_VISIBLE_DEVICES=1 python -m lsh.train_hashcode dataset.name="msnbc294_4" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.4  hashcode_training.QA_MARGIN=1.0) & 
# (CUDA_VISIBLE_DEVICES=1 python -m lsh.train_hashcode dataset.name="msnbc294_4" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.45  hashcode_training.QA_MARGIN=1.0) & 
# (CUDA_VISIBLE_DEVICES=1 python -m lsh.train_hashcode dataset.name="msnbc294_4" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.5  hashcode_training.QA_MARGIN=1.0) & 
# (CUDA_VISIBLE_DEVICES=1 python -m lsh.train_hashcode dataset.name="msnbc294_4" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.55  hashcode_training.QA_MARGIN=1.0) & 
# (CUDA_VISIBLE_DEVICES=1 python -m lsh.train_hashcode dataset.name="msnbc294_4" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.6  hashcode_training.QA_MARGIN=1.0) & 
# (CUDA_VISIBLE_DEVICES=1 python -m lsh.train_hashcode dataset.name="msnbc294_4" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.65  hashcode_training.QA_MARGIN=1.0) & 
# (CUDA_VISIBLE_DEVICES=1 python -m lsh.train_hashcode dataset.name="msnbc294_4" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.7  hashcode_training.QA_MARGIN=1.0) & 
# (CUDA_VISIBLE_DEVICES=1 python -m lsh.train_hashcode dataset.name="msnbc294_4" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.75  hashcode_training.QA_MARGIN=1.0) & 
# (CUDA_VISIBLE_DEVICES=1 python -m lsh.train_hashcode dataset.name="msnbc294_4" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.8  hashcode_training.QA_MARGIN=1.0) & 
# (CUDA_VISIBLE_DEVICES=1 python -m lsh.train_hashcode dataset.name="msnbc294_4" dataset.rel_mode="fhash"  dataset.embed_dim=294   hashing.hcode_dim=64 hashcode_training.hidden_layers=[]  hashing.FUNC="dot" hashing.name="DPRH_Trained" hashing.num_hash_tables=10 training.patience=50 hashcode_training.LOSS_TYPE="query_agnostic" hashcode_training.QA_subset_size=8  hashcode_training.FENCE=0.1 hashcode_training.DECORR=0.85  hashcode_training.QA_MARGIN=1.0) & 
